In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.chdir("D:\\Mahindra")

In [3]:
train=pd.read_csv("train.csv",na_values=["?",","])

In [4]:
test=pd.read_csv("test.csv",na_values=["?",","])

In [5]:
train.shape

(341424, 24)

In [6]:
test.shape

(146765, 23)

In [7]:
train.head(200)

,reservation_id,booking_date,checkin_date,checkout_date,channel_code,main_product_code,numberofadults,numberofchildren,persontravellingid,resort_region_code,...,state_code_residence,state_code_resort,total_pax,member_age_buckets,booking_type_code,memberid,cluster_code,reservationstatusid_code,resort_id,amount_spent_per_room_night_scaled
0,07659f3758d8aee27f5a7e2887adeacb67021cb95ada1b...,05/04/18,05/04/18,06/04/18,3,1,2,0,46,3,...,7.0,3,3,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,C,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,7.706428
1,03930f033646d073462b35d411616323597715ac4fc398...,23/01/15,11/04/15,16/04/15,1,1,2,0,46,3,...,7.0,5,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,39fa9ec190eee7b6f4dff1100d6343e10918d044c75eac...,6.662563
2,d145a32920e6587ad95bfe299d80c0affa268220535aaf...,28/01/15,01/02/15,05/02/15,1,1,2,0,47,1,...,7.0,1,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,7.871602
3,cfd77f44811ed62f25a220b53324cdbafc662a4c9e5f04...,02/05/15,11/06/15,16/06/15,1,1,2,2,46,2,...,7.0,2,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,5.344943
4,937cff9e4dcfc2459620153dfc8b9962ac22bea67dfb29...,02/09/15,14/12/15,19/12/15,1,1,2,0,46,2,...,7.0,2,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.059346
5,cc8f05558362b7589004e57044e8b558bd228fc70da5b0...,01/12/15,12/01/16,13/01/16,1,1,2,0,47,1,...,7.0,6,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,8.167707
6,6827da5d76c626deeed81eb9f3afef635db4c17c9cbea0...,20/01/16,20/01/16,21/01/16,3,1,2,0,46,2,...,7.0,9,1,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,ff5a1ae012afa5d4c889c50ad427aaf545d31a4fac04ff...,6.449838
7,b89547398bfff6b8e99939fbeb20ddb55aa2e43ebce9e4...,22/08/16,20/10/16,25/10/16,1,1,2,2,46,1,...,7.0,6,4,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,7.046172
8,3706793a0263706fe541b6e7f3b681be363f0b7e2bdc63...,10/09/16,18/09/16,24/09/16,1,1,2,0,45,2,...,7.0,10,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,0b918943df0962bc7a1824c0555a389347b4febdc7cf9d...,5.394203
9,1f797a715ff7788cc8162fb033ee0eca345a2209b27593...,03/08/16,21/11/16,24/11/16,1,1,2,0,45,1,...,7.0,1,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,6.561412
10,08e9f5f901e56de363bf53db5c4a76e44a6393076b03de...,03/02/17,28/02/17,01/03/17,2,1,2,0,46,2,...,7.0,9,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,a68b412c4282555f15546cf6e1fc42893b7e07f271557c...,6.820005
11,c105019a45cdeb19b232342e7ec68d784c6592e70f2978...,23/09/17,18/10/17,20/10/17,2,1,2,0,46,2,...,7.0,2,4,F,2,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,6.624450
12,e8d4f0130804217a1c4c2c3159ff66157605adf4c7a39e...,25/01/18,25/01/18,26/01/18,3,1,2,0,46,3,...,7.0,3,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,A,A,7f2253d7e228b22a08bda1f09c516f6fead81df6536eb0...,7.476229
13,e9db2546714291299aa8da26df4f81f28ca4c455a91617...,28/01/18,06/04/18,08/04/18,2,1,2,0,46,3,...,7.0,5,3,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,4ec9599fc203d176a301536c2e091a19bc852759b255bd...,4.139637
14,7542ff11ed65615f42840dec421f2ecb3522e54035b494...,05/04/18,05/04/18,06/04/18,3,1,2,0,45,1,...,8.0,6,4,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,F,C,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...,9.932153
15,821a5e5313029b1bbec6ec738a1b34d6d14c82fca97c47...,05/04/18,08/03/12,11/03/12,3,1,2,0,45,1,...,8.0,6,3,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,F,C,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...,3.218876
16,4e7d0fc7ea7811ac481b17ed54d7d11fcaf640bc600306...,05/04/18,06/04/18,07/04/18,2,1,4,0,46,1,...,8.0,6,4,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,9.684040
17,76a2e0c0f49152e076c5bf055eee7383603614708cda3c...,21/01/15,21/01/15,23/01/15,3,1,2,0,47,1,...,8.0,4,4,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,F,A,e7f6c011776e8db7cd330b54174fd76f7d0216b612387a...,7.275342
18,0dd890143db371136a5a088d4c0b262801db7251a7ef59...,03/08/15,13/10/15,16/10/15,1,1,2,0,46,2,...,8.0,9,4,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,B,A,ff5a1ae012afa5d4c889c50ad427aaf545d31a4fac04ff...,5.175076
19,03602d384e3772575c44b64467b4cc2102cdbb9100a2b1...,03/08/15,09/10/15,13/10/15,1,1,2,0,46,2,...,8.0,9,4,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,B,A,624b60c58c9d8bfb6ff1886c2fd605d2adeb6ea4da5760...,7.461757
20,4a8949c84efb8a437d5e121507fafd3d7dcc1634ec311c...,24/11/16,18/01/17,22/01/17,1,1,2,0,47,3,...,8.0,3,2,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,A,A,7f2253d7e228b22a08bda1f09c516f6fead81df6536eb0...,4.436426
21,065ff246f6b06b07e9d87eeee4e6a072da55f0ede015c1...,24/11/16,22/01/17,25/01/17,1,1,2,0,47,3,...,8.0,3,2,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,A,A,3e1e967e9b793e908f8eae83c74dba9bcccce6a5535b4b...,5.945255
22,238e0c0b012aef01bba4b1d8180ba4b484df7f914a0705...,24/11/16,25/01/17,27/01/17,1,1,2,0,47,3,...,8.0,3,2,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,A,A,9f14025af0065b30e47e23ebb3b491d39ae8ed17d33739...,6.253348
23,2fff0ec0cf2be2da0dbb88e3f9e2b3a5909e4cf3c56562...,30/12/17,19/01/18,22/01/18,2,1,2,0,47,1,...,8.0,6,3,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,F,A,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...,7.953208
24,7b8d2e8b14ccb8290e8ba7372fb7706109527461011011...,22/10/18,07/11/18,09/11/18,1,1,4,0,46,2,...,8.0,2,4,H,1,7b68caeb153ac83aeab0b9a679709c558d57a6c9d2bdf6...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,8.526070
25,2877561c300c5787fbdc9e787b7ecafa3da23c30324442...,05/04/18,05/04/18,06/04/18,3,2,2,0,45,1,...,2.0,11,4,D,1,0fb5e9e87638ac401e88ea0115114182614151218a0147...,F,A,e29c9c180c6279b0b02abd6a1801c7c04082cf486ec027...,10.211829
26,f6cb98ae0a42565f5ad2eca77febfc7643945d75107ef3...,25/03/15,05/04/15,07/04/15,1,2,2,2,47,2,...,2.0,2,4,D,1,0fb5e9e87638ac401e88ea0115114182614151218a0147...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.453072
27,19b1b7295f760003e7e5dbed4d551008c9208078119f54...,28/03/15,02/04/15,05/04/15,1,2,2,2,45,2,...,2.0,2,4,D,1,0fb5e9e87638ac401e88ea0115114182614151218a0147...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.562046
28,9546b2afef44eba27c14e64f2b14ddb908ec9757b36063...,22/02/16,27/03/16,29/03/16,1,2,4,3,45,1,...,2.0,6,4,D,1,0fb5e9e87638ac401e88ea0115114182614151218a0147...,F,A,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...,9.278027
29,37c8fba5af17196ba6745e5c30b6e78b2c1ed9fd3ca026...,05/10/16,17/10/16,20/10/16,1,2,2,2,45,2,...,2.0,7,4,D,1,0fb5e9e87638ac401e88ea0115114182614151218a0147...,C,A,da4ea2a5506f2693eae190d9360a1f31793c98a1adade5...,6.859993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,96359c3ee796594a976f5634b202957560ec450f7e683b...,19/09/14,01/01/15,03/01/15,3,1,2,0,45,3,...,9.0,5,4,F,2,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,F,A,39fa9ec190eee7b6f4dff1100d6343e10918d044c75eac...,9.034065
171,5373e059a8b96008c7c29eab98b9b223e34f710b112da5...,21/03/15,07/06/15,10/06/15,3,1,3,1,45,1,...,9.0,6,4,F,2,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,8.361264
172,f6fdd5727b66318f404b31116426669624ef22a1f5af15...,21/03/15,10/06/15,13/06/15,3,1,3,1,45,1,...,9.0,6,4,F,2,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,F,A,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...,8.382071
173,ae0b7690b00e1268d3d52f84ad092fb91aa05add4910f9...,08/09/15,09/11/15,15/11/15,3,1,4,0,45,2,...,9.0,2,4,F,1,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,D,A,6208ef0f7750c111548cf90b6ea1d0d0a66f6bff40dbef...,8.159066
174,fd1a9f7c660e9183e1e98e323b167162847c5bb1779df1...,07/05/16,07/06/16,11/06/16,3,1,4,0,47,1,...,9.0,6,5,F,1,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,8.669214
175,7ef5496bd978d80929712b07f56a95cb1560a3cb2948e2...,03/05/18,28/06/18,01/07/18,3,1,4,0,45,2,...,9.0,7,5,F,1,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,C,A,9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e47...,8.984583
176,1376fcd6c63fc57fa6c63a65453b1b76d2850f06f6362a...,15/11/18,28/12/18,01/01/19,1,1,4,0,47,1,...,9.0,1,2,F,1,d163362586a8068aa4ebac50f555435f15f34094b1f4cd...,E,A,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,9.392344
177,f6254dcb4c3c82ab9d201f36bf956e5d7743961ba79f38...,29/09/14,05/01/15,09/01/15,3,2,4,0,45,2,...,4.0,2,4,D,1,e454785497002283f7e266dba3533ad710fae8fca0b91c...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.445885
178,854645f6e692268bd7b9bb9f28c8e1c622e29dcf600ebc...,25/09/18,19/10/18,21/10/18,1,2,4,0,45,3,...,4.0,3,7,D,1,e454785497002283f7e266dba3533ad710fae8fca0b91c...,F,A,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,8.372977
179,e6bd9e6d573105d99090051389fced1b73b3c55f337e82...,29/09/14,19/01/15,21/01/15,3,3,5,0,45,1,...,7.0,1,3,F,1,e8605e347010e7c1144e6c1375df364602cbb1102299e0...,E,A,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,7.976875
180,63fa24cfaca74b2794c740c98159da3953706dfba88341...,29/09/14,27/01/15,29/01/15,3,2,5,0,45,2,...,8.0,2,2,H,1,a6dd1ba85b00506b2346a00d1eb4246fc24901c641b93f...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,8.091829
181,8fd6714e7ee9038f8500eb05f6f1411a5356a2b85cd860...,14/02/16,30/04/16,03/05/16,1,2,2,0,46,1,...,8.0,6,2,H,1,a6dd1ba85b00506b2346a00d1eb4246fc24901c641b93f...,F,A,49d180ecf56132819571bf39d9b7b342522a2ac6d23c14...,7.454863
182,9e707d6a7229d803fdf718a7d356a933bc855cc36648ca...,05/09/17,14/10/17,17/10/17,2,2,4,0,47,1,...,8.0,6,2,H,1,a6dd1ba85b00506b2346a00d1eb4246fc24901c641b93f...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,7.705951
183,8c490108de1d961d71215f8b7a3bfd9622217400a7fe24...,07/10/17,09/12/17,13/12/17,1,2,2,0,47,1,...,8.0,6,3,H,1,a6dd1ba85b00506b2346a00d1eb4246fc24901c641b93f...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,8.856941
184,ec8e8de9f6c257f683de91d7b1ea0249092f58fd8f4afe...,31/01/19,03/02/19,05/02/19,3,2,2,0,46,1,...,8.0,11,2,H,1,a6dd1ba85b00506b2346a00d1eb4246fc24901c641b93f...,F,A,e29c9c180c6279b0b02abd6a1801c7c04082cf486ec027...,8.651960
185,f4e06578bcb6d5ff08717fe4029f6f092b4564b353236f...,30/09/14,10/01/15,12/01/15,3,1,2,1,45,3,...,4.0,5,2,F,1,7d9f87d723d290e5743e1be8affdaa1def7ced869fefae...,F,B,4ec9599fc203d176a301536c2e091a19bc852759b255bd...,7.463154
186,26c0c0900418821be0178d02a2f9d20bc2260b331ec0a4...,30/09/14,15/01/15,18/01/15,3,3,2,1,45,2,...,8.0,2,3,D,1,047be68917c9e86b00e566221819d9409722cd6ad71513...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.181242
187,0b73afe3a20c8dd8dd3761a0a55d135176107923cfbea4...,02/01/15,27/02/15,01/03/15,3,3,4,0,45,2,...,8.0,7,7,D,1,047be68917c9e86b00e566221819d9409722cd6ad71513...,C,A,9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e47...,8.516356
188,09d159b3dd1bef678e0149af5538683637669f95760a6e...,01/10/15,28/01/16,31/01/16,3,3,3,0,45,2,...,8.0,7,3,D,1,047be68917c9e86b00e566221819d9409722cd6ad71513...,C,A,da4ea2a5506f2693eae190d9360a1f31793c98a1adade5...,7.053277
189,eae0b547657337a89cd77816a3e1164a039fd10432b115...,03/03/17,21/03/17,22/03/17,2,3,4,0,47,1,...,8.0,1,2,D,1,047be68917c9e86b00e566221819d9409722cd6ad71513...,E,A,81b8a03f97e8787c53fe1a86bda042b6f0de9b0ec9c093...,8.335129
190,19dd6f38828a21360678d37bf8f01a8eda7ed65a281cd7...,11/09/17,22/09/17,24/09/17,1,3,2,0,47,2,...,8.0,7,2,D,1,047be68917c9e86b00e566221819d9409722cd6ad71513...,C,A,da4ea2a5506f2693eae190d9360a1f31793c98a1adade5...,7.454347
191,5e98e0b0849f5203481b51605214f38d9a9e217428d60d...,30/09/14,30/01/15,04/02/15,3,3,2,0,46,1,...,NaN,1,2,H,1,ed9a075109f7d3c997a60f493d8b667f7962c75faa58a1...,E,A,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,3.520816
192,6b95e6e7de39c1db30bd7f7e13bb1042c57f0f77a9b044...,10/12/14,20/02/15,24/02/15,1,3,2,0,47,3,...,NaN,3,2,H,2,ed9a075109f7d3c997a60f493d8b667f7962c75faa58a1...,A,A,ef2d127de37b942baad06145e54b0c619a1f22327b2ebb...,7.519136
193,b467322f2507c8c4ec5e578258a8d88d94fc71d75a7717...,18/07/15,03/08/15,06/08/15,1,3,2,2,46,2,...,NaN,7,2,H,1,ed9a075109f7d3c997a60f493d8b667f7962c75faa58a1...,C,A,da4ea2a5506f2693eae190d9360a1f31793c98a1adade5...,4.840743
194,872817cc65f7a4734d13669d482da767ba51dd0a811cde...,27/01/16,15/02/16,17/02/16,1,3,2,0,47,2,...,NaN,7,2,H,1,ed9a075109f7d3c997a60f493d8b667f7962c75faa58a1...,C,A,da4ea2a5506f2693eae190d9360a1f31793c98a1adade5...,6.629165
195,7bf0288cb74b06ba8b85b467b683dd3266bf6a4c0edb88...,23/11/16,25/01/17,26/01/17,2,3,2,0,46,1,...,NaN,1,3,H,1,ed9a075109f7d3c997a60f493d8b667f7962c75faa58a1...,E,A,c75cb66ae28d8ebc6eded002c28a8ba0d06d3a78c6b5cb...,7.284073
196,55980e142f03513df31a143ede33e6d78fa1023bb36022...,30/09/14,01/01/15,03/01/15,3,2,2,2,45,1,...,25.0,1,4,D,1,b585011fa0ebfb8b7bae4f3d696e50006a9eb257447cea...,E,A,c6f3ac57944a531490cd39902d0f777715fd005efac9a3...,7.525769
197,a826162f02fc7ef87364274bc22d19710a95244f61d5f3...,30/09/14,03/01/15,05/01/15,3,2,2,2,45,1,...,25.0,1,4,D,1,b585011fa0ebfb8b7bae4f3d696e50006a9eb257447cea...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,8.324996
198,c71d04e007f547d9f8e4cb20b836440dfad397822c5f68...,23/02/17,17/03/17,19/03/17,3,2,3,0,45,3,...,25.0,3,4,D,1,b585011fa0ebfb8b7bae4f3d696e50006a9eb257447cea...,A,A,ef2d127de37b942baad06145e54b0c619a1f22327b2ebb...,8.121927
199,b6cb45d47902f002f96b32bc0a37174d2679923f0ff6a5...,29/08/18,18/10/18,20/10/18,2,2,2,2,45,2,...,25.0,9,4,D,1,b585011fa0ebfb8b7bae4f3d696e50006a9eb257447cea...,B,A,a68b412c4282555f15546cf6e1fc42893b7e07f271557c...,8.060114

In [8]:
import datetime as dt

In [9]:
train['checkout_date']=pd.to_datetime(train['checkout_date'],format='%d/%m/%y')
train['checkin_date']=pd.to_datetime(train['checkin_date'],format='%d/%m/%y')

test['checkout_date']=pd.to_datetime(test['checkout_date'],format='%d/%m/%y')
test['checkin_date']=pd.to_datetime(test['checkin_date'],format='%d/%m/%y')

In [11]:
train.head(10)

,reservation_id,booking_date,checkin_date,checkout_date,channel_code,main_product_code,numberofadults,numberofchildren,persontravellingid,resort_region_code,...,state_code_residence,state_code_resort,total_pax,member_age_buckets,booking_type_code,memberid,cluster_code,reservationstatusid_code,resort_id,amount_spent_per_room_night_scaled
0,07659f3758d8aee27f5a7e2887adeacb67021cb95ada1b...,05/04/18,2018-04-05,2018-04-06,3,1,2,0,46,3,...,7.0,3,3,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,C,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,7.706428
1,03930f033646d073462b35d411616323597715ac4fc398...,23/01/15,2015-04-11,2015-04-16,1,1,2,0,46,3,...,7.0,5,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,39fa9ec190eee7b6f4dff1100d6343e10918d044c75eac...,6.662563
2,d145a32920e6587ad95bfe299d80c0affa268220535aaf...,28/01/15,2015-02-01,2015-02-05,1,1,2,0,47,1,...,7.0,1,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,7.871602
3,cfd77f44811ed62f25a220b53324cdbafc662a4c9e5f04...,02/05/15,2015-06-11,2015-06-16,1,1,2,2,46,2,...,7.0,2,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,5.344943
4,937cff9e4dcfc2459620153dfc8b9962ac22bea67dfb29...,02/09/15,2015-12-14,2015-12-19,1,1,2,0,46,2,...,7.0,2,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.059346
5,cc8f05558362b7589004e57044e8b558bd228fc70da5b0...,01/12/15,2016-01-12,2016-01-13,1,1,2,0,47,1,...,7.0,6,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,8.167707
6,6827da5d76c626deeed81eb9f3afef635db4c17c9cbea0...,20/01/16,2016-01-20,2016-01-21,3,1,2,0,46,2,...,7.0,9,1,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,ff5a1ae012afa5d4c889c50ad427aaf545d31a4fac04ff...,6.449838
7,b89547398bfff6b8e99939fbeb20ddb55aa2e43ebce9e4...,22/08/16,2016-10-20,2016-10-25,1,1,2,2,46,1,...,7.0,6,4,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,7.046172
8,3706793a0263706fe541b6e7f3b681be363f0b7e2bdc63...,10/09/16,2016-09-18,2016-09-24,1,1,2,0,45,2,...,7.0,10,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,0b918943df0962bc7a1824c0555a389347b4febdc7cf9d...,5.394203
9,1f797a715ff7788cc8162fb033ee0eca345a2209b27593...,03/08/16,2016-11-21,2016-11-24,1,1,2,0,45,1,...,7.0,1,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,6.561412

In [16]:
train.dtypes

reservation_id                                 object
booking_date                                   object
checkin_date                           datetime64[ns]
checkout_date                          datetime64[ns]
channel_code                                    int64
main_product_code                               int64
numberofadults                                  int64
numberofchildren                                int64
persontravellingid                              int64
resort_region_code                              int64
resort_type_code                                int64
room_type_booked_code                           int64
roomnights                                      int64
season_holidayed_code                         float64
state_code_residence                          float64
state_code_resort                               int64
total_pax                                       int64
member_age_buckets                             object
booking_type_code                               int64
memberid                                       object
cluster_code                                   object
reservationstatusid_code                       object
resort_id                                      object
amount_spent_per_room_night_scaled            float64
days_spend                            timedelta64[ns]
days_spend_new                               category
dtype: object

In [9]:
#label encoding of target to perform svc

from sklearn.preprocessing import LabelEncoder
T = LabelEncoder()

In [10]:
train.head(10)

,reservation_id,booking_date,checkin_date,checkout_date,channel_code,main_product_code,numberofadults,numberofchildren,persontravellingid,resort_region_code,...,state_code_residence,state_code_resort,total_pax,member_age_buckets,booking_type_code,memberid,cluster_code,reservationstatusid_code,resort_id,amount_spent_per_room_night_scaled
0,07659f3758d8aee27f5a7e2887adeacb67021cb95ada1b...,05/04/18,05/04/18,06/04/18,3,1,2,0,46,3,...,7.0,3,3,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,C,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,7.706428
1,03930f033646d073462b35d411616323597715ac4fc398...,23/01/15,11/04/15,16/04/15,1,1,2,0,46,3,...,7.0,5,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,39fa9ec190eee7b6f4dff1100d6343e10918d044c75eac...,6.662563
2,d145a32920e6587ad95bfe299d80c0affa268220535aaf...,28/01/15,01/02/15,05/02/15,1,1,2,0,47,1,...,7.0,1,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,7.871602
3,cfd77f44811ed62f25a220b53324cdbafc662a4c9e5f04...,02/05/15,11/06/15,16/06/15,1,1,2,2,46,2,...,7.0,2,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,5.344943
4,937cff9e4dcfc2459620153dfc8b9962ac22bea67dfb29...,02/09/15,14/12/15,19/12/15,1,1,2,0,46,2,...,7.0,2,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,D,A,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,7.059346
5,cc8f05558362b7589004e57044e8b558bd228fc70da5b0...,01/12/15,12/01/16,13/01/16,1,1,2,0,47,1,...,7.0,6,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,8.167707
6,6827da5d76c626deeed81eb9f3afef635db4c17c9cbea0...,20/01/16,20/01/16,21/01/16,3,1,2,0,46,2,...,7.0,9,1,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,ff5a1ae012afa5d4c889c50ad427aaf545d31a4fac04ff...,6.449838
7,b89547398bfff6b8e99939fbeb20ddb55aa2e43ebce9e4...,22/08/16,20/10/16,25/10/16,1,1,2,2,46,1,...,7.0,6,4,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,F,A,b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d6...,7.046172
8,3706793a0263706fe541b6e7f3b681be363f0b7e2bdc63...,10/09/16,18/09/16,24/09/16,1,1,2,0,45,2,...,7.0,10,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,B,A,0b918943df0962bc7a1824c0555a389347b4febdc7cf9d...,5.394203
9,1f797a715ff7788cc8162fb033ee0eca345a2209b27593...,03/08/16,21/11/16,24/11/16,1,1,2,0,45,1,...,7.0,1,2,F,1,3d1539e56495b6991f0a3ef5a61ca3d03ce4fff7380e9a...,E,A,535fa30d7e25dd8a49f1536779734ec8286108d115da50...,6.561412

In [11]:
train.columns

Index(['reservation_id', 'booking_date', 'checkin_date', 'checkout_date',
       'channel_code', 'main_product_code', 'numberofadults',
       'numberofchildren', 'persontravellingid', 'resort_region_code',
       'resort_type_code', 'room_type_booked_code', 'roomnights',
       'season_holidayed_code', 'state_code_residence', 'state_code_resort',
       'total_pax', 'member_age_buckets', 'booking_type_code', 'memberid',
       'cluster_code', 'reservationstatusid_code', 'resort_id',
       'amount_spent_per_room_night_scaled'],
      dtype='object')

In [12]:
dropping=['reservation_id','booking_date','checkout_date','checkin_date','memberid','resort_id']

In [13]:
train=train.drop(dropping,axis=1)
test=test.drop(dropping,axis=1)

In [14]:
train.dtypes

channel_code                            int64
main_product_code                       int64
numberofadults                          int64
numberofchildren                        int64
persontravellingid                      int64
resort_region_code                      int64
resort_type_code                        int64
room_type_booked_code                   int64
roomnights                              int64
season_holidayed_code                 float64
state_code_residence                  float64
state_code_resort                       int64
total_pax                               int64
member_age_buckets                     object
booking_type_code                       int64
cluster_code                           object
reservationstatusid_code               object
amount_spent_per_room_night_scaled    float64
dtype: object

In [15]:
train.isnull().sum()

channel_code                             0
main_product_code                        0
numberofadults                           0
numberofchildren                         0
persontravellingid                       0
resort_region_code                       0
resort_type_code                         0
room_type_booked_code                    0
roomnights                               0
season_holidayed_code                  114
state_code_residence                  4764
state_code_resort                        0
total_pax                                0
member_age_buckets                       0
booking_type_code                        0
cluster_code                             0
reservationstatusid_code                 0
amount_spent_per_room_night_scaled       0
dtype: int64

In [16]:
train['member_age_buckets'] = T.fit_transform(train.member_age_buckets)
train['cluster_code'] = T.fit_transform(train.cluster_code)
train['reservationstatusid_code'] = T.fit_transform(train.reservationstatusid_code)

In [17]:
test['member_age_buckets'] = T.fit_transform(test.member_age_buckets)
test['cluster_code'] = T.fit_transform(test.cluster_code)
test['reservationstatusid_code'] = T.fit_transform(test.reservationstatusid_code)

In [18]:
train.dtypes

channel_code                            int64
main_product_code                       int64
numberofadults                          int64
numberofchildren                        int64
persontravellingid                      int64
resort_region_code                      int64
resort_type_code                        int64
room_type_booked_code                   int64
roomnights                              int64
season_holidayed_code                 float64
state_code_residence                  float64
state_code_resort                       int64
total_pax                               int64
member_age_buckets                      int32
booking_type_code                       int64
cluster_code                            int32
reservationstatusid_code                int32
amount_spent_per_room_night_scaled    float64
dtype: object

In [19]:
test.isnull().sum()

channel_code                   0
main_product_code              0
numberofadults                 0
numberofchildren               0
persontravellingid             0
resort_region_code             0
resort_type_code               0
room_type_booked_code          0
roomnights                     0
season_holidayed_code         35
state_code_residence        2260
state_code_resort              0
total_pax                      0
member_age_buckets             0
booking_type_code              0
cluster_code                   0
reservationstatusid_code       0
dtype: int64

In [20]:
train['season_holidayed_code'].fillna(train['season_holidayed_code'].mean(),inplace=True)
train['state_code_residence'].fillna(train['state_code_residence'].mean(),inplace=True)

test['season_holidayed_code'].fillna(test['season_holidayed_code'].mean(),inplace=True)
test['state_code_residence'].fillna(test['state_code_residence'].mean(),inplace=True)

In [30]:
#import pandas_profiling as pp
#pp.ProfileReport(train)

In [31]:
#train1=train.drop_duplicates(subset='FlightNumber',keep='last')

In [21]:
test.dtypes

channel_code                  int64
main_product_code             int64
numberofadults                int64
numberofchildren              int64
persontravellingid            int64
resort_region_code            int64
resort_type_code              int64
room_type_booked_code         int64
roomnights                    int64
season_holidayed_code       float64
state_code_residence        float64
state_code_resort             int64
total_pax                     int64
member_age_buckets            int32
booking_type_code             int64
cluster_code                  int32
reservationstatusid_code      int32
dtype: object

In [22]:
#split data
from sklearn.model_selection import train_test_split

In [23]:
# Divide in to train and test
train_target=train["amount_spent_per_room_night_scaled"]
train1=train.drop('amount_spent_per_room_night_scaled', axis=1)
#from sklearn.model_selection import train_test_split  
train2,val2,train_target2,val_target2 = train_test_split(train1, train_target, test_size=0.20)

In [24]:
from sklearn.preprocessing import StandardScaler
num_values=train2.select_dtypes(['int64','float64','int32','float32']).columns
scaler = StandardScaler()
scaler.fit(train2[num_values])
#scaler.fit(val2[num_values])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 250 decision trees
rf = RandomForestRegressor(n_estimators = 1000,max_features=4, random_state = 42,max_depth=2)
# Train the model on training data
rf.fit(train2,train_target2)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
           max_features=4, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=None, oob_score=False,
           random_state=42, verbose=0, warm_start=False)

In [26]:
from math import sqrt

In [27]:
from sklearn.metrics import mean_squared_error

predictions11 = rf.predict(train2)

meanSquaredError=mean_squared_error(train_target2, predictions11)
print("MSE:", meanSquaredError)
rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.1394892467358233
RMSE: 1.0674686162767613

In [28]:
from sklearn.metrics import mean_squared_error

predictions1 = rf.predict(val2)

meanSquaredError=mean_squared_error(val_target2, predictions1)
print("MSE:", meanSquaredError)
rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.1389091662928439
RMSE: 1.0671968732585586

In [29]:
feat_importances = pd.Series(rf.feature_importances_, index=train2.columns)
feat_importances = feat_importances.sort_values(ascending=False)
feat_importances.nlargest(20).plot(kind='barh')

In [ ]:
#Saving predictions

test_pred2= rf.predict(test)
test_pred2

In [ ]:
tst = pd.read_csv('sample_submission.csv')
sub = pd.DataFrame()
sub['reservation_id'] = tst.reservation_id
sub['amount_spent_per_room_night_scaled'] = test_pred2
sub.to_csv('trail2.csv')

In [42]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(train2, train_target2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [43]:
predictionsreg = reg.predict(train2)
meanSquaredError=mean_squared_error(train_target2, predictionsreg)
print("MSE:", meanSquaredError)

rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.0482595182603553
RMSE: 1.023845456238565

In [44]:
from sklearn.metrics import mean_squared_error

predictionsreg = reg.predict(val2)
meanSquaredError=mean_squared_error(val_target2, predictionsreg)
print("MSE:", meanSquaredError)

rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.0393482020987281
RMSE: 1.0194842824186787

In [45]:
#Saving predictions

test_predlog= reg.predict(test)
test_predlog

array([7.81296421, 7.52571112, 7.44011609, ..., 7.97834558, 7.2014645 ,
       7.50119006])

In [46]:
tst = pd.read_csv('sample_submission.csv')
sub = pd.DataFrame()
sub['reservation_id'] = tst.reservation_id
sub['amount_spent_per_room_night_scaled'] = test_predlog
sub.to_csv('trail4.csv')

In [ ]:
test.head(2)

In [47]:
from sklearn import linear_model
Ridge = linear_model.Ridge(alpha=0)
Ridge.fit(train2, train_target2)

Ridge(alpha=0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [48]:
from sklearn.metrics import mean_squared_error

predictions = Ridge.predict(train2)

meanSquaredError=mean_squared_error(train_target2, predictions)
print("MSE:", meanSquaredError)
rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.0482595182603553
RMSE: 1.023845456238565

In [49]:
from sklearn.metrics import mean_squared_error

predictions = Ridge.predict(val2)

meanSquaredError=mean_squared_error(val_target2, predictions)
print("MSE:", meanSquaredError)
rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.0393482020987281
RMSE: 1.0194842824186787

In [50]:
from sklearn import linear_model
lasso = linear_model.Lasso(alpha=0)
lasso.fit(train2, train_target2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:478: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

Lasso(alpha=0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [51]:
from sklearn.metrics import mean_squared_error

predictions1 = lasso.predict(val2)

meanSquared=mean_squared_error(val_target2, predictions1)
print("MSE:", meanSquaredError)
rootMeanSquare = sqrt(meanSquared)
print("RMSE:", rootMeanSquaredError)

MSE: 1.0393482020987281
RMSE: 1.0194842824186787

In [203]:
from sklearn import tree

model4 = tree.DecisionTreeRegressor(max_depth=9, max_features=7)   
model4.fit(train2, train_target2)

DecisionTreeRegressor(criterion='mse', max_depth=9, max_features=7,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [204]:
from sklearn.metrics import mean_squared_error

predictionstree1 = model4.predict(train2)
meanSquaredErrors=mean_squared_error(train_target2, predictionstree1)
print("MSE:", meanSquaredError)

from math import sqrt

rootMeanSquaredErrors = sqrt(meanSquaredErrors)
print("RMSE:", rootMeanSquaredError)

MSE: 1.0283349040632788
RMSE: 1.0140684908147373

In [205]:
from sklearn.metrics import mean_squared_error

predictionstree = model4.predict(val2)
meanSquaredError=mean_squared_error(val_target2, predictionstree)
print("MSE:", meanSquaredError)

from math import sqrt

rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 1.01843347847209
RMSE: 1.0091746521153264

In [ ]:
#Saving predictions

test_predlog= reg.predict(test)
test_predlog